### PR TITLE
Full flexbox support

### PR DESCRIPTION
**Pull request by outoftime**
Adds parser support for the remaining flexbox properties:

* `align-content`
* `align-items`
* `align-self`
* `flex-direction`
* `flex-flow`
* `flex-wrap`
* `justify-content`
* `order`

### CODE REVIEW

**Comment by fidian** [comment]
I really appreciate the time you invested in making this pull request!  Sorry that I didn't get to it earlier.  For the majority of the time you've been waiting, I was on vacation with no internet access.

Merged!

**Comment by outoftime** [comment]
@fidian not to worry and thank you! Any chance we could cut a release now that there’s full Flex support?

**Comment by fidian** [comment]
Published.

**Comment by outoftime** [comment]
Awesome, thanks!

**Pull request merged**
