### PR TITLE
Add support for background-position-x and background-position-y

### PR DESCRIPTION
**Pull request by jwang1919**
Happy Holidays!

Addresses the bug in Popcode: popcodeorg/popcode#1461

I intentionally omitted support for side-relative values because of incompatibility with Chrome.

### CODE REVIEW

**Comment by jwang1919** [comment]
@fidian Ah nice catch. No worries about the late reply, I didn't get a chance to work on this PR until now so we're both tardy here.

Didn't know about using bin/parse before. Made changes and now it looks good on my side.

**Comment by fidian** [comment]
Awesome, thanks!

**Comment by jwang1919** [comment]
@fidian Thanks for merging! Can you also update the package version btw?

**Comment by fidian** [comment]
Absolutely. Sorry, I forgot to do it earlier. 0.3.19 has been published.

--
Tyler Akins

**Comment by jwang1919** [comment]
@fidian Hey again. I tried updating the library to 0.3.19 in the Popcode project but it's failing. Noticed on https://www.npmjs.com/package/PrettyCSS latest version is still on 0.3.17

**Comment by fidian** [comment]
I went back to the terminal window where I published the repository. You're right, it was not sent to NPM. I've corrected the problem.

It's not reflected on the NPM website yet, but that should happen soon.

**Pull request merged**
